"""SDTM export module - CDISC SDTM format generation.

This module provides SDTM (Study Data Tabulation Model) export capabilities
for clinical trial data generated by TrialSim.

Domains supported:
- DM: Demographics
- AE: Adverse Events
- EX: Exposure
- SV: Subject Visits
"""

from trialsim.formats.sdtm.domains import (
    SDTMDomain,
    SDTMVariable,
    DM_VARIABLES,
    AE_VARIABLES,
    EX_VARIABLES,
    SV_VARIABLES,
    DOMAIN_VARIABLES,
    get_domain_variables,
    get_required_variables,
)
from trialsim.formats.sdtm.exporter import (
    ExportConfig,
    ExportFormat,
    ExportResult,
    SDTMExporter,
    export_to_sdtm,
    create_sdtm_exporter,
)

__all__ = [
    # Domains
    "SDTMDomain",
    "SDTMVariable",
    "DM_VARIABLES",
    "AE_VARIABLES",
    "EX_VARIABLES",
    "SV_VARIABLES",
    "DOMAIN_VARIABLES",
    "get_domain_variables",
    "get_required_variables",
    # Exporter
    "ExportConfig",
    "ExportFormat",
    "ExportResult",
    "SDTMExporter",
    "export_to_sdtm",
    "create_sdtm_exporter",
]
